version: '3.4'

services:
  commands:
    build:
      context: NQNBackend
      dockerfile: Dockerfile
    healthcheck:
      test: "[ -f no_health ] || [ \"$$(curl -f http://localhost:8888/health)\" = \"0\" ]"
      retries: 3
      start_period: 5m
    depends_on:
      - elasticsearch
    restart: always
    networks: [app]

  frontend:
    build:
      context: NQNFrontend
      dockerfile: Dockerfile
    restart: always
    networks: [app]

  guild_builder:
    build:
      context: GuildBuilder
      dockerfile: Dockerfile
    restart: always
    networks: [app]

  gateway_0:
    build:
      context: GatewayHandler
      dockerfile: Dockerfile
      args:
        INSTANCES: 3
        CURRENT: 0
        SHARD_COUNT: 6
    restart: always
    networks: [app]

  gateway_1:
    build:
      context: GatewayHandler
      dockerfile: Dockerfile
      args:
        INSTANCES: 3
        CURRENT: 1
        SHARD_COUNT: 6
    restart: always
    networks: [app]

  gateway_2:
    build:
      context: GatewayHandler
      dockerfile: Dockerfile
      args:
        INSTANCES: 3
        CURRENT: 2
        SHARD_COUNT: 6
    restart: always
    networks: [app]

  status:
    build:
      context: StatusUpdate
      dockerfile: Dockerfile
    restart: always
    networks: [app]

  members:
    build:
      context: MemberKeeper
      dockerfile: Dockerfile
    restart: always
    networks: [app]

  pack_names:
    build:
      context: PackEmoteUpdater
      dockerfile: Dockerfile
    restart: always
    networks: [app]

  reacts:
    build:
      context: ReactionHandler
      dockerfile: Dockerfile
    restart: always
    networks: [app]

  state:
    build:
      context: StateKeeper
      dockerfile: Dockerfile
    restart: always
    networks: [app]

  emote_hasher:
    build:
      context: EmoteHasher
      dockerfile: Dockerfile
    restart: always
    networks: [app]


  cron:
    build:
      context: CronScheduler
      dockerfile: Dockerfile
    volumes:
      - pgbackups:/backup/
    restart: always
    networks: [app]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOST="0.0.0.0"
      - SERVER_BASEPATH="/kibana"
      - SERVER_REWRITEBASEPATH=true
      - xpack.security.enabled=false
    depends_on:
      - elasticsearch
    ports:
      - "5602:5601"
    restart: always
    networks: [app]

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.nginx
    restart: always
    ports:
     - "8002:80"
    networks: [app]

  haproxy:
    build:
      context: .
      dockerfile: haproxy/Dockerfile.haproxy
    restart: always
    networks: [app]

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    volumes:
      - 'redis_data:/bitnami/redis/data'
    restart: always
    networks: [app]


  redis_persistent:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    volumes:
      - 'persistent_redis_data:/bitnami/redis/data'
    restart: always
    networks: [app]

  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile.postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    networks: [app]

  rabbit:
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbit_data:/var/lib/rabbitmq/
    restart: always
    networks: [app]

  netdata:
    image: netdata/netdata
    hostname: blue.nqn
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    restart: always
    networks: [app]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms8192m -Xmx8192m"
      - 'path.repo=/usr/share/elasticsearch/backup'
      - network.publish_host=127.0.0.1
      - cluster.initial_master_nodes=127.0.0.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esbackups:/usr/share/elasticsearch/backup/backup
    restart: always
    networks: [app]

networks:
  app:
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24


volumes:
  esdata:
    driver: local
  esbackups:
    driver: local
  redis_data:
    driver: local
  persistent_redis_data:
    driver: local
  postgres_data:
    driver: local
  pgbackups:
    driver: local
  rabbit_data:
    driver: local
