version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: nqn-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - 'path.repo=/usr/share/elasticsearch/backup'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always
    networks: [app]

  backend:
    build:
      context: NQNBackend
      dockerfile: Dockerfile
    healthcheck:
      test: "[ \"$$(curl -f http://localhost:8888/health)\" = \"0\" ]"
      retries: 3
      start_period: 30m
    depends_on:
      - elasticsearch
    volumes:
     - lmdbdata:/lmdb
    restart: always
    networks: [app]

  frontend:
    build:
      context: NQNFrontend
      dockerfile: Dockerfile
    restart: always
    networks: [app]

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    environment:
      - ELASTICSEARCH_HOSTS=http://nqn-elasticsearch:9200
      - SERVER_HOST="0.0.0.0"
      - SERVER_BASEPATH="/kibana"
      - xpack.security.enabled=false
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    restart: always
    networks: [app]

  netdata:
    image: netdata/netdata
    hostname: blue.nqn
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    restart: always
    networks: [app]

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.nginx
    restart: always
    ports:
     - "8001:80"
    networks: [app]

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  app:
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.2/24


volumes:
  esdata:
    driver: local
  lmdbdata:
    driver: local
