version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks: [app]

  backend:
    build:
      context: BetterE6Backend
      dockerfile: Dockerfile
    depends_on:
     - elasticsearch
    restart: always
    networks: [app]

  frontend:
    build:
      context: BetterE6Frontend
      dockerfile: Dockerfile
    restart: always
    networks: [app]

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    depends_on:
     - backend
    ports:
     - "80:80"
    networks: [app]

networks:
  app:
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.1/24


volumes:
  esdata:
    driver: local