version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: nqn-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks: [app]

  backend:
    build:
      context: NQNBackend
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
    volumes:
     - lmdbdata:/lmdb
    restart: always
    networks: [app]

  frontend:
    build:
      context: NQNFrontend
      dockerfile: Dockerfile
    depends_on:
     - backend
    restart: always
    networks: [app]

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    environment:
      - ELASTICSEARCH_HOSTS=http://nqn-elasticsearch:9200
      - SERVER_HOST="0.0.0.0"
      - SERVER_BASEPATH="/kibana"
      - xpack.security.enabled=false
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks: [app]

  netdata:
    image: netdata/netdata
    hostname: blue.nqn
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.nginx
    restart: always
    depends_on:
     - frontend
     - backend
     - kibana
     - netdata
    ports:
     - "8001:80"
    networks: [app]

networks:
  app:
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.2/24


volumes:
  esdata:
    driver: local
  lmdbdata:
    driver: local
