#FROM postgres:12
FROM timescale/timescaledb-ha:pg12-latest

USER root
RUN usermod -u 999 postgres
USER postgres

COPY postgres/pg_hba.conf /var/lib/postgresql/data/
COPY postgres/postgresql.conf /var/lib/postgresql/data/
